import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ArweaveWalletKit } from "arweave-wallet-kit";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: 'puzzlegame_telegram',
  description: "Generated by create next app",
  viewport : "width=device-width,user-scalable=no,initial-scale=1,minimum-scale=1,maximum-scale=1,minimal-ui=true",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ArweaveWalletKit>{children}</ArweaveWalletKit>
      </body>
    </html>
  );
}
